---
apiVersion: v1
kind: Service
metadata:
  name: api-tradingview-service
  namespace: airflow

spec:
  ports:
    - name: 6001-to-6001-tcp
      port: 6001
      protocol: TCP
      targetPort: 6000
  selector:
    app: api-tradingview
  sessionAffinity: None
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-tradingview
  namespace: airflow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-tradingview
  template:
    metadata:
      labels:
        app: api-tradingview

    spec:
      containers:
        - name: api-tradingview
          image:  # path to kafka producer docker image in GCP docker image registry
          ports:
            - containerPort: 6000
          command: ['sh', '-c', 'echo "Running Tradingview Kafka service..."; while :; do sleep 3600 ; done']
